name: example
description: An XMTP example app.
publish_to: none
version: 0.0.1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.10.0
  blockies_ethereum: ^0.0.2
  convert: ^3.1.1
  drift: ^2.5.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.18.6
  go_router: ^6.2.0
  http: ^0.13.5
  intl: ^0.18.0
  path: ^1.8.2
  path_provider: ^2.0.13
  qr_flutter: ^4.0.0
  quiver: ^3.2.1
  retry: ^3.1.0
  shared_preferences: ^2.0.18
  sqlite3_flutter_libs: ^0.5.13
  url_launcher: ^6.1.10
  walletconnect_dart: ^0.0.11
  web3dart: ^2.6.1
  xmtp:
    path: '../'

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
