name: xmtp
description: XMTP client SDK for Flutter applications.
# Version replaced at build time in release.yml
version: 0.0.0
repository: https://github.com/xmtp/xmtp-flutter

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  async: ^2.10.0
  grpc: ^3.1.0
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  pointycastle: ^3.6.2
  quiver: ^3.2.1
  web3dart: ^2.6.1
  xmtp_proto: ^3.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:
